openapi: 3.0.0
info:
  title: Formula 1 Mock API
  version: "1.0.0"
  description: Mock API based on Ergast Developer API structure for local development

tags:
  - name: Seasons
    description: Endpoints for managing Formula 1 seasons and related data

servers:
  - url: http://localhost:5001/api
    description: Local development server
  - url: https://formula-1-cn81.onrender.com/api
    description: Production server

paths:
  /seasons:
    get:
      tags:
        - Seasons
      summary: Get all seasons
      responses:
        "200":
          description: List of F1 seasons

  /seasons/{season}:
    get:
      tags:
        - Seasons
      summary: Get details for a specific season
      parameters:
        - name: season
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Season detail
        "404":
          description: Season not found

  /seasons/{season}/races:
    get:
      tags:
        - Seasons
      summary: Get all races for a season
      parameters:
        - name: season
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of races
